server.port=7777

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.url=jdbc:sqlserver://CO-APPSQL03d:1433;databaseName=ETL_PracticeDB;encryption=true;trustServerCertificate=true
spring.datasource.username=ETLPracticeDB_User
spring.datasource.password=Ede@3VCxRFgY

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
